version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: test-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: test_username
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
