CREATE TABLE IF NOT EXISTS links (
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    url TEXT NOT NULL UNIQUE,
    source_id INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    CONSTRAINT fk_source FOREIGN KEY (source_id) REFERENCES sources(id) ON DELETE CASCADE
);

