CREATE TABLE IF NOT EXISTS ips (
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    ip INET NOT NULL UNIQUE,
    source_id INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    CONSTRAINT fk_source FOREIGN KEY (source_id) REFERENCES sources(id) ON DELETE CASCADE
);
